myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nathmankindscrumy/', include('nathmankindscrumy.urls')),
    path('websocket/', include('websocket.urls')),
]

nathmankindscrumy/urls.py
from django.urls import path, include
from . import views

app_name = 'nathmankindscrumy'

urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>', views.move_goal, name='movegoal'),
    path('addgoal', views.add_goal, name='addgoal'),
    path('home', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls'))
]

nathmankindscrumy/models.py
from django.db import models
from django import forms
import random
from django.contrib.auth.models import User

# Create your models here.


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=200)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=200)
    goal_id = models.IntegerField(unique=True)
    created_by = models.CharField(max_length=200)
    moved_by = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user = models.ForeignKey(User,  related_name='user',
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=200)
    created_by = models.CharField(max_length=200)
    moved_from = models.CharField(max_length=200)
    moved_to = models.CharField(max_length=200)
    time_of_action = models.CharField(max_length=200)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.CASCADE)

    def __str__(self):
        return self.created_by

nathmankindscrumy/forms.py
from nathmankindscrumy.models import ScrumyGoals, ScrumyHistory, GoalStatus
from django.contrib.auth.models import User, Group
from django import forms


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    group_choices = forms.ChoiceField(choices=[(choice.pk, choice) for choice in Group.objects.all()],
                                      widget=forms.RadioSelect)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password', 'group_choices']


class CreateGoalForm(forms.ModelForm):
    '''user = forms.ChoiceField(choices=[(choice.pk, choice) for choice in User.objects.all()],
    widget=forms.RadioSelect)
    user = forms.ModelMultipleChoiceField(queryset=User.objects.all())'''
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', ]

    def __init__(self, *args, **kwargs):
        super(CreateGoalForm, self).__init__(*args, **kwargs)
        self.fields['user'] = forms.ModelChoiceField(
            queryset=User.objects.all())
        self.fields['goal_status'] = forms.ModelChoiceField(
            queryset=GoalStatus.objects.all())

class DevCreateGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name']
    
    def __init__(self, *args, **kwargs):
        super(DevCreateGoalForm, self).__init__(*args, **kwargs)
        queryset=GoalStatus.objects.all()
        self.fields['goal_status'] = forms.ChoiceField(
            choices=[(choice.pk, choice) for choice in queryset[:1]])
    
# class MoveGoalForm(forms.ModelForm):
#     goal_status = forms.ModelChoiceField(queryset=GoalStatus.objects.all())

#     class Meta:
#         model = GoalStatus
#         fields = ['goal_status']
# ChangeGoalForm
class MoveGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(
        choices=[(choice.pk, choice) for choice in queryset])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']
    
class DevMoveGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(
        choices=[(choice.pk, choice) for choice in queryset[:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']

class QAMoveGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(
        choices=[(choice.pk, choice) for choice in queryset.order_by('-id')[:3][::-1]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']

nathmankindscrumy/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.http import Http404
import random
from django.contrib.auth.models import User, Group
from .models import GoalStatus, ScrumyGoals, ScrumyHistory
from .forms import SignupForm, CreateGoalForm, MoveGoalForm, DevCreateGoalForm, DevMoveGoalForm, QAMoveGoalForm

# Create your views here.


def index(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            group = form.cleaned_data['group_choices']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user_group = Group.objects.get(id=int(group))
            user_group.user_set.add(user)
            return render(request, 'nathmankindscrumy/success.html', {})
    else:
        form = SignupForm()

    return render(request, 'nathmankindscrumy/index.html', {'form': form})


def move_goal(request, goal_id):
    if request.user.is_authenticated:
        current_user = request.user
        user_group = request.user.groups.all()[0].name
        dev_grp = Group.objects.get(name = 'Developer')
        admin_grp = Group.objects.get(name = 'Admin')
        qa_grp = Group.objects.get(name = 'Quality Assurance')
        owner_grp = Group.objects.get(name = 'Owner')
        dev = dev_grp.name
        admin = admin_grp.name
        qa = qa_grp.name
        owner = owner_grp.name
        try:
            goal = ScrumyGoals.objects.get(goal_id = goal_id)
            if user_group == admin or user_group == owner:
                if request.method == 'POST':
                    form = MoveGoalForm(request.POST)
                    if form.is_valid():
                        selected_status = form.save(commit=False)
                        status = form.cleaned_data.get('goal_status')
                        choice = GoalStatus.objects.get(id = int(status))
                        goal.goal_status = choice
                        goal.save()
                        return render(request, 'nathmankindscrumy/move_success.html', {'goal': goal})
                else:
                    form = MoveGoalForm()
            elif user_group == dev and request.user == goal.user:
                if request.method == 'POST':
                    form = DevMoveGoalForm(request.POST)
                    if form.is_valid():
                        selected_status = form.save(commit=False)
                        status = form.cleaned_data.get('goal_status')
                        choice = GoalStatus.objects.get(id = int(status))
                        goal.goal_status = choice
                        goal.save()
                        return render(request, 'nathmankindscrumy/move_success.html', {'goal': goal})
                else:
                    form = DevMoveGoalForm()
            elif user_group == qa:
                if request.method == 'POST':
                    form = QAMoveGoalForm(request.POST)
                    if form.is_valid():
                        selected_status = form.save(commit=False)
                        status = form.cleaned_data.get('goal_status')
                        choice = GoalStatus.objects.get(id = int(status))
                        goal.goal_status = choice
                        goal.save()
                        return render(request, 'nathmankindscrumy/move_success.html', {'goal': goal})
                else:
                    form = QAMoveGoalForm()
            else:
                return render(request, 'nathmankindscrumy/error.html', {})
            return render(request, 'nathmankindscrumy/movegoal.html', {'form': form})
        except ScrumyGoals.DoesNotExist:
            return render(request, 'nathmankindscrumy/exception.html', {'error': 'A record with that goal id does not exist'})
    
    else:
        return HttpResponse('Please login')
    # try:
    #     obj = ScrumyGoals.objects.get(goal_id=goal_id)
    # except ScrumyGoals.DoesNotExist:
    #     return render(request, 'nathmankindscrumy/exception.html', {'error': 'A record with that goal id does not exist'})
    


def add_goal(request):
    current_user = request.user
    user_group = request.user.groups.all()[0].name
    dev_grp = Group.objects.get(name = 'Developer')
    admin_grp = Group.objects.get(name = 'Admin')
    qa_grp = Group.objects.get(name = 'Quality Assurance')
    owner_grp = Group.objects.get(name = 'Owner')
    dev = dev_grp.name
    admin = admin_grp.name
    qa = qa_grp.name
    owner = owner_grp.name
    if user_group == dev or user_group == qa or user_group == owner:
        if request.method == 'POST':
            form = DevCreateGoalForm(request.POST)
            if form.is_valid():
                goal = form.save(commit=False)
                user = current_user
                goal_stat = form.cleaned_data.get('goal_status')
                status = GoalStatus.objects.get(id = int(goal_stat))
                goal_name = form.cleaned_data['goal_name']
                goal.goal_id = random.randint(1000, 9999)
                goal.goal_status = status
                goal.user = user
                goal.save()
                return render(request, 'nathmankindscrumy/goal_success.html', {})
        else:
            form = DevCreateGoalForm()
        
        
            #==========
    elif user_group == admin:
        if request.method == 'POST':
            form = CreateGoalForm(request.POST)
            if form.is_valid():
                goal = form.save(commit=False)
                user = form.cleaned_data.get('user')
                goal_stat = form.cleaned_data.get('goal_status')
                goal_name = form.cleaned_data['goal_name']
                goal.goal_id = random.randint(1000, 9999)
                goal.goal_status = goal_stat
                goal.user = user
                goal.save()
                return render(request, 'nathmankindscrumy/goal_success.html', {})
        else:
            form = CreateGoalForm()

    return render(request, 'nathmankindscrumy/addgoal.html', {
            'form': form,
            'current_user': current_user,
            'user_grp': user_group
        })


def home(request):
    current_user = request.user
    user_group = request.user.groups.all()[0].name
    if request.user.is_authenticated:
        users = User.objects.all()
        '''
        1 = Weekly Goal,
        2 = Daily Goal,
        3 = verify goal,
        4 = done goal
        '''

        all_goal = []
        for goal in users:
            user_goals = goal.user.all()
            all_goal.append((user_goals))
        context = {
            'users': users,
            'current_user': current_user,
            'all_goals': all_goal,
            'user_group': user_group
        }
        return render(request, 'nathmankindscrumy/home.html', context)
    else:
        return render(request, 'registration/login.html', {'error': 'Please login'})

nathmankindscrumy/templates/nathmankindscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Add Goal</title>
  </head>
  <body>
    <p>Current User: {{current_user}}</p>
    <p>Group: {{ user_grp}}</p>
    <form action="" method="post">
      {% csrf_token %} {% for field in form %}
      <p>
        {{ field.label_tag }} <br />
        {{ field }}
      </p>
      {% endfor %}
      <button type="submit">Add Goal</button>
    </form>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Error</title>
  </head>
  <body>
    <p>Sorry! You can't move other user's goal</p>
    <p>Back to <a href="{% url 'nathmankindscrumy:home' %}">Home</a></p>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/exception.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Error Page</title>
  </head>
  <body>
    <p>{{ error }}</p>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/goal_success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Success Page</title>
  </head>
  <body>
    <p>Your goal has been created successfully</p>
    <p><a href="{% url 'nathmankindscrumy:home' %}">Home</a></p>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>ScrumyApp</title>
    <style>
      table,
      th,
      td {
        border: 1px solid black;
      }
      button {
        background-color: #051782;
        border: none;
        margin-top: 8px;
        padding: 8px 12px;
        border-radius: 12px;
      }
      button a {
        text-decoration: none;
        color: #ffffff;
      }
    </style>
  </head>
  <body>
    <h1>
      Current User: {{ current_user }}
      <span
        style="color: #ffffff; padding: 2px 4px; border-radius: 8px; font-family: Arial, Helvetica, sans-serif; font-weight: 200; background-color: rgb(45, 119, 2);"
        >User Group: {{ user_group }}</span
      >
    </h1>
    <!-- new way to build the table -->

    <table>
      <tr>
        <th>User</th>
        <th>Weekly Goal</th>
        <th>Daily Goal</th>
        <th>Verify Goal</th>
        <th>Done Goal</th>
      </tr>

      <!-- {% if all_goals %} {% for goal in all_goals %} {% for a_goal in goal %}
      <tr>
        <td>{{ a_goal.user }}</td>

        {% if a_goal.goal_status_id == 1 %}
        <td>{{ a_goal.goal_id }}) {{ a_goal.goal_name }}</td>
        {% else %}
        <td>--</td>
        {% endif %} {% if a_goal.goal_status_id == 2 %}
        <td>{{ a_goal.goal_id }}) {{ a_goal.goal_name }}</td>
        {% else %}
        <td>--</td>
        {% endif %} {% if a_goal.goal_status_id == 3 %}
        <td>{{ a_goal.goal_id }}) {{ a_goal.goal_name }}</td>
        {% else %}
        <td>--</td>
        {% endif %} {% if a_goal.goal_status_id == 4 %}
        <td>{{ a_goal.goal_id }}) {{ a_goal.goal_name }}</td>
        {% else %}
        <td>--</td>
        {% endif %}
      </tr>

      {% endfor %} {% endfor %} {% endif %} -->

      {% if users %} {% for user in users %}
      <tr>
        <td>{{ user.username }}</td>
        <td>
          {% for goal in user.user.all %} {% if goal.goal_status.id == 1 %}
          <p>
            <a href="{% url 'nathmankindscrumy:movegoal' goal.goal_id %}"
              >{{ goal.goal_id }} - {{ goal}}
            </a>
          </p>
          {% endif %} {% endfor %}
        </td>
        <td>
          {% for goal in user.user.all %} {% if goal.goal_status.id == 2 %}
          <p>
            <a href="{% url 'nathmankindscrumy:movegoal' goal.goal_id %}"
              >{{ goal.goal_id }} - {{ goal}}
            </a>
          </p>
          {% endif %} {% endfor %}
        </td>
        <td>
          {% for goal in user.user.all %} {% if goal.goal_status.id == 3 %}
          <p>
            <a href="{% url 'nathmankindscrumy:movegoal' goal.goal_id %}"
              >{{ goal.goal_id }} - {{ goal}}
            </a>
          </p>
          {% endif %} {% endfor %}
        </td>
        <td>
          {% for goal in user.user.all %} {% if goal.goal_status.id == 4 %}
          <p>
            <a href="{% url 'nathmankindscrumy:movegoal' goal.goal_id %}"
              >{{ goal.goal_id }} - {{ goal}}
            </a>
          </p>
          {% endif %} {% endfor %}
        </td>
      </tr>
      {% endfor %} {% endif %}
    </table>

    <button>
      <a href="{% url 'nathmankindscrumy:addgoal' %}">Add Goal</a>
    </button>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
    <style>
        ul {
            display: inline-block;
            list-style-type: none;
            padding-left: 8px;
        }
    </style>
</head>
<body>
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }} <br>
        {{ field }}

        {% if field.help_text %}
        <small> {{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{error}}</p>
    {% endfor %}
    </p>
    {% endfor %}

    <button type="submit">Sign Up</button>
    <p>Already have an account? <a href="{% url 'nathmankindscrumy:login' %}">Login</a></p>
</form>

</body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/move_success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Goal Move</title>
  </head>
  <body>
    <p>
      <span style="font-size: 24px; font-weight: 400; color: rgb(50, 126, 0);"
        >{{goal.goal_name}}</span
      >
      has now being moved to
      <span style="font-size: 24px; font-weight: 400; color: rgb(50, 126, 0);"
        >{{goal.goal_status}}</span
      >
      successfully
    </p>
    <p>Go to <a href="{% url 'nathmankindscrumy:home' %}">Home</a></p>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Move goal</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <p>Select the status you want</p>
      {{ form }}
      <button type="submit">Move Goal</button>
    </form>
  </body>
</html>

nathmankindscrumy/templates/nathmankindscrumy/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Success Page</title>
  </head>
  <body>
    <p>Your account has been created successfully</p>
    <p><a href="{% url 'nathmankindscrumy:login' %}">Login</a></p>
  </body>
</html>